export const LOADING = 'LOADING';
export const OK = 'OK';
export const WRONG = 'WRONG';
export const CONNECT = 'CONNECT';
export const INSTALL = 'INSTALL';

export const SET_FOOTER_DATA = 'SET_FOOTER_DATA';
export const SET_MANAGE_DATA = 'SET_MANAGE_DATA';
export const SET_WORKLOCK_DATA = 'SET_WORKLOCK_DATA';

export const SET_ACCOUNT_AND_NU = 'SET_ACCOUNT_AND_NU';

export const SET_RESTAKE_CLICKED = 'SET_RESTAKE_CLICKED';
export const SET_RESTAKE_STATUS = 'SET_RESTAKE_STATUS';
export const SET_WINDDOWN_CLICKED = 'SET_WINDDOWN_CLICKED';
export const SET_WINDDOWN_STATUS = 'SET_WINDDOWN_STATUS';
